### ISSUE TITLE
How NOT to use issues.

### ISSUE THREAD

**Issue by Quadragintillion** [GoobersInc/gooberproxy-plus#1]
the fact that you morons are spamming random servers with stupid disconnect requests and filling up logs with crap

**Comment by 112batman** [comment]
What makes you feel the need to open an issue on software that is provided to you free of charge, made by people that are not getting paid, wasting valuable time of contributers. Not only does your issue not provide any relevant information, it's also an unjustified personal attack. Furthermore your issue is based exclusively on on untrue information. Please do not come back until you actually understand what this piece of software does and are able to formulate usefull issues in a mature manner.

**Comment by Quadragintillion** [comment]
No, you guys are literally spamming servers with this. Some of the IPs that this is coming from links directly to enderschesi's server, so I would say I do in fact understand what this piece of software does.

**Comment by Quadragintillion** [comment]
And it is COMPLETELY justified.

**Comment by 112batman** [comment]
You seem to still not understand what this piece of software does, I advise you look into that before opening issues on it. It appears as if you've never used it yourself, I'd also like to clarify that this is obviously not a way to contact enderschesi or other contributers for personal matters. And no, the personal attack is not justified, firstly you're attacking everyone who contributed to this project,  whilst only one of them has anything to do with your "issue", secondly scanning for Minecraft servers or similar internet scanning activities are in no way harmful and if your server is not able to handle the couple extra log lines produced by this maybe you shouldn't be running a server in the first place. And I would once again like to ask you to use issues how they're intended, this means, knowing what you're opening an issue on, it is clear that you still don't know what this piece of software does.
